name: Generacion

on:
  push:
    branches:
      - Ejercicio3

jobs:
  generar-codigo:
    runs-on: ubuntu-latest

    steps:
      # Paso 1
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Paso 3
      - name: Generar código del servidor OpenAPI
        run: java -jar openapi-generator-cli.jar generate -i api.yaml -g python-flask -o ./openapi_server

      # Paso 4
      - name: Comprimir código generado
        run: zip -r openapi_server.zip openapi_server

      # Paso 5
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: openapi_server
          path: openapi_server.zip
